### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by chavisam** [jorgepardor/4GInstagramWithBootstrap#1]
Hola Jorge!. 
El ejercicio está muy bien. Veo que has pillado cómo funciona Bootstrap. 

Ten en cuenta que para que el ejercicio quede bonito y correcto... las imágenes deberían tener todas el mismo ancho y alto

**Comment by jorgepardor** [comment]
Hola Chavi, gracias por las correcciones. 

Tenía dos dudas con respecto a ese ejercicio (no se si te acuerdas que el otro día en clase te pregunté cuando podía preguntar para no interrumpir a Marcos).

Te las voy a escribir por aquí, pero si quieres lo hablamos luego, cuando tu quieras:

1.- Tengo algunas dudas sobre la version de bootstrap en los ejercicios de la escuela. En toda la documentación hacen referencia a bootstrap 5, pero en los ejercicios he tenido que resolver ciertas partes con elementos del 4, que según leo en la documentación, han cambiado en el 5. 

Me refiero concretamente a que me parece que el masonry grid que se usaba en bs4 ya no se usa igual en el 5 (por eso dejé la vista esa "sin terminar"). De todas maneras, haré la corrección que me dices y te la subiré en el transcurso del día. Me pasó también en el ejercicio de la website colaborativa con el tag "jumbrotron", que creo que en bs5 ha cambiado la forma de aplicar ese tipo de maquetación. 

2.- Ahora si una duda concreta de este ejercicio, la navegación con "pills" me dió problemas para cambiarle el color. Intenté cambiarlo con bg-color, text-color y con varias cosas que vi en internet, pero en todos los casos me impedía que el estado highlighted o selected se vieran resaltados correctamente. Si tienes un momento a lo largo de los próximos días y sabes la respuesta, me gustaría que me dijeras que estoy haciendo mal. 

Voy a subir la corrección y te dejo otro mensaje.

Un abrazo. 

Jorge

**Comment by jorgepardor** [comment]
Hola! 

He ajustado las imágenes en la vista de grid para que se enseñen todas cuadradas, como hace Instagram. También cambié un poco los colores de las nav-pills para que tuvieran algo mas de coherencia con el resto de la página. 

Si le ves cualquier cosa rara, avísame.

Saludos!

Jorge
